IMAGES_VERSION=221006HF-202306221501
ARS_IMAGE_FILE="arserver-${IMAGES_VERSION}-image.tar.gz"
MIDTIER_IMAGE_FILE="midtier-${IMAGES_VERSION}-image.tar.gz"
AR_DB_IMAGE_FILE="ar-db-${IMAGES_VERSION}-image.tar.gz"
ARS_IMAGE="arserver:${IMAGES_VERSION}"
MIDTIER_IMAGE="midtier:${IMAGES_VERSION}"
AR_DB_IMAGE="ar-db:${IMAGES_VERSION}"